/** Mythra Glyphnet symbols shipped under /public/glyphs. */

export const GLYPH_SLUGS = [
  "air",
  "amulet",
  "ant",
  "anubis",
  "apollo",
  "artemis",
  "ash",
  "athena",
  "authority",
  "bag",
  "bear",
  "bee",
  "bell",
  "blood",
  "brahma",
  "bridge",
  "butterfly",
  "cave",
  "centaur",
  "chalice",
  "chameleon",
  "chaos",
  "circle",
  "circle-wholeness",
  "cliff",
  "comet",
  "constellation",
  "coyote",
  "crab",
  "cross",
  "crow",
  "crown",
  "crystal",
  "crystal-frequency-amplifier",
  "cube",
  "death",
  "deer",
  "desert",
  "diamond",
  "dionysus",
  "dolphin",
  "dragon",
  "dragonfly",
  "dream",
  "drum",
  "durga",
  "eagle",
  "earth",
  "elephant",
  "eros",
  "eye",
  "fate",
  "father",
  "fire",
  "fish",
  "flower",
  "flute",
  "fool",
  "forest",
  "fox",
  "freyja",
  "frog",
  "fruit",
  "ganesha",
  "gateway",
  "gecko",
  "hades",
  "harp",
  "hawk",
  "heart",
  "hera",
  "hermit",
  "horse",
  "horus",
  "house",
  "hummingbird",
  "iguana",
  "infinity",
  "isis",
  "jaguar",
  "justice",
  "kali",
  "key",
  "king",
  "labyrinth",
  "lakshmi",
  "lamp",
  "leaves",
  "lightning",
  "lion",
  "lizard",
  "loki",
  "lotus",
  "maiden",
  "mandala",
  "mask",
  "mirror",
  "moon",
  "mother",
  "mountain",
  "mushroom",
  "night",
  "nuwa",
  "oak",
  "oak-ancestral-strength",
  "ocean",
  "octopus",
  "odin",
  "orb",
  "order",
  "oshun",
  "osiris",
  "owl",
  "pack",
  "pentacle",
  "persephone",
  "persona",
  "phoenix",
  "pyramid",
  "queen",
  "quetzalcoatl",
  "rainbow",
  "raven",
  "roots",
  "rose",
  "sage",
  "saraswati",
  "scorpion",
  "seahorse",
  "serpent",
  "shadow",
  "shaman",
  "shango",
  "shark",
  "shiva",
  "sky",
  "solitude",
  "song",
  "spider",
  "spiral",
  "staff",
  "stag",
  "star",
  "storm",
  "sun",
  "swan",
  "sword",
  "talisman",
  "tezcatlipoca",
  "thanatos",
  "thor",
  "thoth",
  "thunderbird",
  "tides",
  "tiger",
  "time",
  "torus",
  "tree",
  "triangle",
  "truth",
  "turtle",
  "unicorn",
  "vine",
  "vishnu",
  "void",
  "volcano",
  "warrior",
  "water",
  "whale",
  "wolf",
  "yantra",
  "yemaya",
  "zeus",
] as const;

export type GlyphSlug = (typeof GLYPH_SLUGS)[number];

export function glyphSrc(slug: GlyphSlug | string): string {
  return `/glyphs/${slug}.svg`;
}

function normalizeKey(name: string): string {
  return name.normalize("NFD").replace(/\p{M}/gu, "").toLowerCase();
}

/** Map a corpus text / tradition name to a preferred glyph. */
const GLYPH_RULES: Array<{ pattern: RegExp; glyph: GlyphSlug }> = [
  { pattern: /tao|te.?ching|tao_te_ching|zhuang|chuang|lao.?tzu|chuang_tzu/i, glyph: "dragon" },
  // Astavakra before generic "gita" so it doesn't inherit Bhagavad Gītā's mark.
  { pattern: /astavakra|ashtavakra|a[sṣ][tṭ][aā]vakra/i, glyph: "hermit" },
  { pattern: /bhagavad/i, glyph: "vishnu" },
  { pattern: /epictetus/i, glyph: "sage" },
  { pattern: /phaedo|plato/i, glyph: "athena" },
  { pattern: /plotinus|ennead/i, glyph: "infinity" },
  { pattern: /milarepa|jetsun.?kahbum|tibet.?s.?great.?yogi/i, glyph: "mountain" },
  { pattern: /tilopa|maha.?mudra|ganges.?mahamudra/i, glyph: "water" },
  { pattern: /heart.?s[uū]tra|prajnaparamita|prajñāpāramitā/i, glyph: "lotus" },
  { pattern: /nagarjuna|madhyamaka|mulamadhyamakakarika|mmk/i, glyph: "void" },
  { pattern: /shantideva|śāntideva|bodhicary/i, glyph: "heart" },
  { pattern: /chandogya|khandogya|khândogya/i, glyph: "sun" },
  { pattern: /isavasya|īśāvāsya|isha.?upani/i, glyph: "circle-wholeness" },
  { pattern: /svetasvatara|śvetāśvatara/i, glyph: "fire" },
  { pattern: /mandukya|māṇḍūkya|gaudapada|gauḍapāda/i, glyph: "moon" },
  { pattern: /upanishad|upaniṣad/i, glyph: "yantra" },
  { pattern: /vijnana|bhairava|vijñāna.?bhairava/i, glyph: "eye" },
  { pattern: /pratyabhij/i, glyph: "mirror" },
  { pattern: /spanda/i, glyph: "tides" },
  { pattern: /tantras[aā]ra|abhinavagupta/i, glyph: "mandala" },
  { pattern: /siva.?s[uū]tra|śiva.?s[uū]tra|shiva.?sutra/i, glyph: "shiva" },
  { pattern: /vijnana|bhairava|shiva|siva|tantra|spanda|yogin[iī]|yogini_hrdaya|pratyabhij/i, glyph: "shiva" },
  { pattern: /heraclitus|fragment/i, glyph: "fire" },
  { pattern: /patanjali|patañjali|yoga.?s[uū]tras?|raja.?yoga/i, glyph: "spiral" },
  { pattern: /ibn|arabi|know yourself/i, glyph: "mirror" },
  { pattern: /confucius|analect/i, glyph: "tree" },
  { pattern: /marcus|meditation/i, glyph: "sage" },
  { pattern: /rumi|poet/i, glyph: "spiral" },
  { pattern: /dogen|dōgen|shobogenzo|shōbōgenzō/i, glyph: "moon" },
  { pattern: /eckhart|meister_eckhart|abegescheidenheit|abgeschiedenheit/i, glyph: "chalice" },
];

function asGlyph(slug: string): GlyphSlug {
  return (GLYPH_SLUGS as readonly string[]).includes(slug) ? (slug as GlyphSlug) : "lotus";
}

export function collectionGlyph(name?: string): GlyphSlug {
  const raw = (name || "").trim();
  if (!raw || raw.toLowerCase() === "all") return "lotus";
  const key = normalizeKey(raw);
  for (const rule of GLYPH_RULES) {
    if (rule.pattern.test(raw) || rule.pattern.test(key)) return asGlyph(rule.glyph);
  }
  return "diamond";
}

/** Stable “random” glyph for a passage — same id always gets the same mark. */
export function unitGlyph(seed?: string): GlyphSlug {
  const key = (seed || "").trim() || "pratibha";
  let h = 2166136261;
  for (let i = 0; i < key.length; i += 1) {
    h ^= key.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  const idx = Math.abs(h) % GLYPH_SLUGS.length;
  return GLYPH_SLUGS[idx]!;
}

/** Home gateway / section ornaments. */
export const GATEWAY_GLYPHS = {
  archive: "gateway",
  dialogue: "eye",
  oracle: "star",
  curriculum: "labyrinth",
} as const satisfies Record<string, GlyphSlug>;
