/**
 * Curated hero lines — up to ten of the strongest sentences per text.
 * Shown when a collection mandala opens; they rotate while the gate is held.
 * Keep each line short enough to sit inside the mandala (roughly 28–140 chars).
 */

type QuoteBank = {
  pattern: RegExp;
  quotes: string[];
};

const HERO_QUOTES: QuoteBank[] = [
  {
    pattern: /futa.?jalon|fuuta.?jaloo|reichardt/i,
    quotes: [
      "He sat between the tomb of the Prophet and the pulpit and leaned his back against the wall.",
      "Until this day grass does not grow on the spot where the fight took place.",
      "Both sat on the ground leaving the mat vacant between them.",
      "They would each have to bear the sins of those who fight on either side on their account.",
      "It is you who have written all these books, and if God will you may still write others.",
      "She continued her prayer. She did not stop, she did not move, she did not fear.",
      "If you are tired, well, let us sit down; you know your gun won't give fire if God be unwilling.",
      "He fears God may not find him in the other world, not in heaven.",
      "He himself does not know to which place he turns unless God the Lord gives him His directions.",
      "You have done mischief sadly; our family and friends are not there.",
    ],
  },
  {
    pattern: /senegalese.?animism|serer|pangool/i,
    quotes: [
      "There is an invisible master of all things.",
      "They believe above all in the spirits, mammam, and they never address themselves to God.",
      "They have two Gods: on one side Takhar, who presides over justice; on the other Tiurakh, who disposes of all goods.",
      "The Serer believe in a future life and in metempsychosis.",
      "Two or three elders of the family deliver speeches, then all go in turn to bid farewell to the deceased and to speak into his ear.",
      "The Serer are deeply attached to their soil.",
      "To render the spirits favorable, one pours milk or millet-water at the foot of the trees or upon consecrated stones.",
      "To render the spirits favorable, one pours libations of milk or millet-water at the foot of the trees or upon consecrated stones.",
      "Never would Serer people displace themselves voluntarily to go live in a foreign land.",
      "Among the presents is an empty canari, a large red earthen jar.",
    ],
  },
  {
    pattern: /pulaar.?texts|gaden|le.?poular/i,
    quotes: [
      "This is what was here; it will be, or it will not be. It is a tale — a thing to be heard.",
      "A flatterer is not a companion; a king is not a comrade; a second wife is not a wife; a stepson is not a son.",
      "Every affair — it is a cause that does it.",
      "If the lies set out early and the truth in the evening, it will overtake the lies.",
      "The heart is not a joint, that it might be bent.",
      "What the cow has eaten is what the heifer suckles.",
      "A single grief does not tear the belly by a single road.",
      "The head, if it has not trusted the razor of God, the razor will not trust the head of God.",
      "What produces fruit begins by flowering.",
      "The cow puts her foot on her young — yet she does not hate.",
    ],
  },
  {
    pattern: /pulaar.?tradition|ful[bɓ]e/i,
    quotes: [
      "Even today, in Wassallah and Kankan, one finds nomad Peuls who have only one cult: that of their herds.",
      "The cleanliness they observe in their cattle-pens has something religious about it.",
      "It is the needs of their herds that determine their displacements.",
      "Through the whole operation the young men must keep the greatest impassibility; it would be dishonor to complain.",
      "Every time Peuls on a journey meet a tomb or a cemetery, they throw as they pass a handful of grass or green leaves.",
      "A Peul never accomplishes an important action without consulting his mother.",
      "The prohibition was instituted by the ancestor at the same time as the clan name.",
      "Always in the midst of their herds, they know them admirably and make themselves loved by them.",
      "In their markets they part only with oxen, never with calves or cows.",
      "A fervent Muslim but not a fanatic, he keeps a continual gravity.",
    ],
  },
  {
    pattern: /attar|mantiq|conference.?of.?the.?birds/i,
    quotes: [
      "We have a king, my friends, whose name is Simurgh, and whose residence is behind Mount Qaf.",
      "A feather from His wing fell on Chinese soil.",
      "Whoever has become a lover should never think of his own life.",
      "These are the seven valleys: Quest, Love, Knowledge, Detachment, Unity, Bewilderment, Poverty and Annihilation.",
      "After the first valley comes the Valley of Love. Whoever sets foot there is plunged into fire.",
      "All who raise their heads in this wilderness draw them from the same collar.",
      "Last comes the Valley of Poverty and Annihilation.",
      "Thirty birds—only thirty out of millions—survive and approach the capital of the Simurgh.",
      "Whoever beholds himself in this mirror sees there his soul and body—sees himself entire.",
      "The hoopoe cried: you who stop at appearances, talk no more of Love.",
    ],
  },
  {
    pattern: /hujwir|kashf.?al.?ma[hḥ]j[uū]b/i,
    quotes: [
      "Knowledge is of two kinds: divine and human.",
      "Poverty has an outward form and an inward reality.",
      "The true Sufi is one who leaves impurity behind.",
      "Unveiling is destruction of the veiled object.",
      "There are two veils: covering, which cannot be removed, and clouding, which is quickly lifted.",
      "Unification is of three kinds: God's unification of God, of His creatures, and people's unification of God.",
      "Maḥq is the annihilation of a person's being in the essence of God.",
      "Gnosis cannot be acquired by ordinary means.",
      "Know that in our time the knowledge of Sufism has fallen out of use.",
      "One person is veiled from the Truth by his essence, so that truth and falsehood appear the same.",
    ],
  },
  {
    pattern: /gospel.?of.?mary/i,
    quotes: [
      "Every nature, every form, every creature exists in and with each other, but they will dissolve again into their own roots.",
      "Sin does not exist, but you are the ones who make sin.",
      "The Son of Humanity exists within you. Follow him.",
      "When Mary said this, she turned their hearts toward the Good.",
      "You are blessed because you did not waver at the sight of me. For where the mind is, there is the treasure.",
      "I was to you just a garment, and you did not recognize me.",
      "Why do you judge me, since I have not judged?",
      "From now on I will receive the rest of the time of the age in silence.",
      "Do you really think that I thought this up by myself in my heart?",
      "If the Savior made her worthy, who are you then to reject her?",
    ],
  },
  {
    pattern: /logia of jesus|new.?testament.?logia/i,
    quotes: [
      "The kingdom of God does not come with observation. Look: the kingdom of God is within you.",
      "Blessed are the pure in heart, for they will see God.",
      "When you pray, go into your inner room, shut the door, and pray to your Father who is in the secret place.",
      "If then your eye is single, your whole body will be full of light.",
      "Come to me, all who labor and are heavy-laden, and I will give you rest.",
      "In the beginning was the Word, and the Word was with God, and the Word was God.",
      "I am the light of the world. Whoever follows me will not walk in the darkness.",
      "In that day you will know that I am in my Father, and you in me, and I in you.",
      "Abide in me, and I in you. Apart from me you can do nothing.",
      "That they may all be one, as you, Father, are in me and I in you.",
    ],
  },
  {
    pattern: /psalm|tehillim|psalter/i,
    quotes: [
      "The heavens recount the glory of El; the firmament tells the work of his hands.",
      "In them he has pitched a tent for the sun.",
      "Let the words of my mouth and the murmur of my heart be toward your pleasure.",
      "YHWH is my shepherd; I lack nothing.",
      "As a deer pants for water-courses, so my being pants for you, God.",
      "Drop, and know that I am God; I will be exalted in the earth.",
      "For with you is the fountain of life; in your light we see light.",
      "Whoever sits in the secret of the Most High lodges in the shadow of Shaddai.",
      "I have soothed and quieted my being like a weaned child upon its mother.",
      "Where can I go from your spirit? And where from your face can I flee?",
    ],
  },
  {
    pattern: /lalla|lal.?ded|lalleshwari|vakyani|vākyāni/i,
    quotes: [
      "Then I saw in my own house a learned man — and that was my lucky star.",
      "Slowly I stopped my breath in the bellows of the throat, and the lamp of knowledge blazed up.",
      "Thou art I, I am Thou — to ask 'Who am I?' is the doubt that kills.",
      "I wearied myself seeking Him, and saw that bolts were on His door.",
      "Foulness I burnt from my soul. Then the name of Lalla spread abroad.",
      "My teacher spoke one precept: from without, enter the inmost part.",
      "Now it is dawn. Seek the Friend.",
      "When the tailor worked his scissors on me piece by piece, I found the way of the Supreme.",
      "He whose mind has become free from duality — he alone has seen the Lord.",
      "When mind itself disappeared, then nothing anywhere was left.",
    ],
  },
  {
    pattern: /bhagavad/i,
    quotes: [
      "You have a right to action, never to its fruits.",
      "The Self is never born, nor does it ever die.",
      "Yoga is skill in action.",
      "Beings are unmanifest in their beginning, manifest in their middle, unmanifest again in their end.",
      "I am the taste in water, the light of the sun and moon.",
      "“My limbs sink, my mouth dries up, my body trembles, and my hair stands on end.",
      "For even of a striving person of discrimination, O son of Kunti, the turbulent senses forcibly carry away the mind.",
      "Content with gain that comes by chance, gone beyond the dualities, free from envy, equal in success and failure — even having acted, one is not bound.",
      "Abandoning without remainder all desires born of intention, restraining the flock of senses on every side by the mind alone — slowly, slowly let one come to.",
      "But higher than that is another being bhāva, the unmanifest beyond the unmanifest, the everlasting — which does not perish when all beings perish.",
    ],
  },
  {
    pattern: /astavakra|ashtavakra|a[sṣ][tṭ][aā]vakra/i,
    quotes: [
      "You are not the body, nor is the body yours. You are awareness.",
      "If you detach yourself from identification with the body, you will rest in your own nature.",
      "Liberation is not a future event. It is the nature of the one who sees.",
      "The world is a painting on the canvas of awareness.",
      "Desirelessness, simple knowing, and stillness — this is liberation.",
      "One who knows with certainty that the changes of being and non-being arise by nature becomes changeless, free of affliction, and effortlessly comes to peace.",
      "Knowing in truth the Self ātman to be one and imperishable avināśin, how can there be delight rati in acquiring wealth or objects artha for one steadfast in.",
      "Not doer, not enjoyer, not bondage, not liberation—witness, untouched, at peace, alone: thus the Upaniṣad declares 'I am.' kartā: agent; bhoktā.",
      "One who is certain that 'I am not the body, nor is the body mine; I am consciousness' — for whom in this world would such a person not be seen as liberated.",
      "Where is existence, where is non-existence, where is oneness, where is duality?",
    ],
  },
  {
    pattern: /ch[aā]ndogya|khandogya/i,
    quotes: [
      "Tat tvam asi — that thou art.",
      "In the beginning this was Being, one without a second.",
      "The finest essence — that is the Self of this whole world.",
      "As rivers flowing into the ocean lose name and form, so the knower, freed from name and form, enters the divine.",
      "As by knowing one lump of clay, all that is made of clay is known.",
      "When the gods and the asuras were contending—both offspring of Prajāpati—the gods then took up the udgītha the elevated Sāman chant, thinking: “By this we.",
      "Therefore, one should form a resolve.",
      "“Put this salt in water, and then come to me in the morning.” He did so.",
      "When a man, dear one, is overcome by illness, his kinsmen gather around him, saying, “Do you know me?",
      "“Dear one, they bring a man seized by the hand.",
    ],
  },
  {
    pattern: /isavasya|[iī][sś][aā]v[aā]sya|isha.?upani/i,
    quotes: [
      "All this, whatsoever moves in this moving world, is pervaded by the Lord.",
      "He who sees all beings in the Self, and the Self in all beings, shrinks from nothing.",
      "Into blinding darkness enter those who worship ignorance; into greater darkness those who delight in knowledge alone.",
      "The face of truth is covered with a golden lid.",
      "He who knows both knowledge and ignorance together crosses death through the one and attains immortality through the other.",
      "All this moving world is pervaded by the Lord.",
      "Those devoted only to ignorance enter darkness; those devoted only to knowledge enter deeper darkness.",
      "Unmoving, one, swifter than mind — the gods did not reach It though moving ahead.",
      "He moved everywhere, bright, bodiless, without wound, without sinews, pure, untouched by evil; the seer, the thinker, the all-pervading, the self-existent.",
      "Into blinding darkness enter those who worship ignorance; into darkness still greater than that enter those who delight in knowledge alone.",
    ],
  },
  {
    pattern: /katha|ka[tṭ]ha/i,
    quotes: [
      "The Self is not attained by the weak, nor by the careless, nor by mere austerity.",
      "Know the Self as the rider, the body as the chariot, the intellect as the charioteer.",
      "Arise, awake, seek the great ones and learn.",
      "That which is never heard of, nor thought, nor known — from that all this has sprung.",
      "The ancient one is not born, does not die; unborn, eternal, he is not slain when the body is slain.",
      "Vaiśvānara, the universal Fire, enters homes as a Brahmin guest.",
      "This, truly, is the finest support; this, truly, is the supreme support.",
      "Just as pure water, poured into pure water, becomes exactly like it, so does the Self become for the sage who truly knows, O Gautama.",
      "Now, Gautama, I shall declare to you this hidden, eternal Brahman, and how the self comes to be after it has met death.",
      "Then Naciketas, having received this knowledge taught by Death, together with the whole discipline of yoga, attained Brahman.",
    ],
  },
  {
    pattern: /brihadaranyaka|b[rṛ]had[aā]ra[nṇ]yaka/i,
    quotes: [
      "Lead me from the unreal to the real, from darkness to light, from death to immortality.",
      "Neti, neti — not this, not this.",
      "When the Self is seen, heard, thought of, and known, all this is known.",
      "As a lump of salt thrown into water dissolves, so the Self has neither inside nor outside.",
      "This Self is dearer than a son, dearer than wealth, dearer than all else.",
      "For truly, fear arises from a second.",
      "This earth is the honey of all beings, and all beings are the honey of this earth.",
      "What is the light of this person?",
      "Hence there is the teaching: Not this, not this.",
      "This Imperishable, O Gārgī, the knowers of Brahman declare to be: not gross, not minute, not short.",
    ],
  },
  {
    pattern: /mundaka|mu[nṇ][dḍ]aka/i,
    quotes: [
      "Two birds, companions, cling to the same tree; one eats the fruit, the other looks on without eating.",
      "Truth alone conquers, not falsehood.",
      "This Self cannot be attained by instruction, nor by intellect, nor by much learning.",
      "When he who is hidden in all beings is seen, the knots of the heart are cut.",
      "Take the bow of the Upaniṣad, set on it the arrow sharpened by meditation, and pierce the imperishable.",
      "Two birds, companions joined together, embrace the same tree.",
      "This whole universe is indeed the Puruṣa: action, austerity, Brahman, the supreme immortal.",
      "Know that one Self alone in whom heaven, earth, and the mid-region are woven, together with mind and all the vital breaths.",
      "In the supreme golden sheath is Brahman: stainless virajam, partless niṣkalam.",
      "Two fair-winged birds, joined companions, cling to the same tree.",
    ],
  },
  {
    pattern: /mandukya|m[aā][nṇ][dḍ][uū]kya|gaudapada|gau[dḍ]ap[aā]da/i,
    quotes: [
      "Aum: this whole world is that syllable.",
      "The fourth is not inward knowing, not outward knowing, not both — unseen, ungraspable, the Self.",
      "There is no dissolution, no birth, none in bondage, no seeker, no one liberated.",
      "The world of duality is mere māyā; the non-dual alone is the truth.",
      "Turiya is the cessation of phenomena — peaceful, auspicious, non-dual.",
      "Om: this imperishable syllable is all this.",
      "It is not born, nor does it die, nor does it undergo transformation anywhere.",
      "That alone is called the Fourth—unborn, immutable, peaceful, non-dual, the supreme highest.",
      "Om — this syllable is all this.",
      "The first quarter is Vaiśvānara — whose sphere is the waking state, who is conscious of the external, who has seven limbs and nineteen mouths, and who.",
    ],
  },
  {
    pattern: /svetasvatara|[sś]vet[aā][sś]vatara/i,
    quotes: [
      "Hear, you who know Brahman: the God who stands in fire, in water, who has entered the whole world.",
      "He is the one who makes the one seed manifold.",
      "The Self, smaller than the small, greater than the great, is hidden in the heart of the creature.",
      "Knowing that God, one is released from all fetters.",
      "He is fire, he is the sun, he is the wind, he is the moon.",
      "Two unborn ones are present: the knower and the non-knower, the lord and the non-lord.",
      "The ṛc-verses abide in the imperishable, highest expanse, wherein all the gods have taken their seats.",
      "The knowers of Brahman ask: What is the cause?",
      "One Deva—the shining Lord—is hidden in all beings: all-pervading, the inner Self antarātman of all beings; the overseer of action karma, the dwelling-place.",
      "For him there is no work to be done, nor any instrument karaṇa found.",
    ],
  },
  {
    pattern: /patanjali|pata[nñ]jali|yoga.?s[uū]tra/i,
    quotes: [
      "Yoga is the stilling of the turnings of the mind.",
      "Then the seer rests in its own true form.",
      "Practice becomes firmly grounded when it is cultivated for a long time, without interruption, with care.",
      "Īśvara is a special self, untouched by afflictions, karma, and their ripening.",
      "When the mind is colored by the object, the object is known.",
      "1.1 Now, the teaching of yoga.",
      "1.31 Suffering, despair, trembling of the limbs, irregular breathing—these accompany distraction vikṣepasahabhuvaḥ.",
      "2.12 Rooted in affliction kleśa, the deposit of action karmāśaya bears fruit in lives seen and unseen.",
      "2.16 Suffering that has not yet come can be avoided.",
      "2.46 Posture āsana is steadiness and ease sthira-sukha.",
    ],
  },
  {
    pattern: /ha[tṭ]ha.?yoga|pradipika|pradīpikā/i,
    quotes: [
      "Haṭha is a stairway for those who would climb to the height of rāja yoga.",
      "When the breath wanders, the mind is unsteady; when the breath is still, the mind is still.",
      "As salt dissolves in water, so the mind that has entered the Self becomes one with it.",
      "The yogi who is freed from all thought remains as if dead to the world — that is liberation.",
      "When the nāḍīs are purified, the body becomes light, the fire of digestion kindles, and the inner sound is heard.",
      "Like a house protecting one from the heat of the sun, Hatha Yoga protects its practisers from the burning heat of the three Tāpas; and, similarly, it is the.",
      "A yogi or yogini desirous of success should keep the knowledge of Hatha Yoga secret; for it becomes potent by concealing, and impotent by exposing.",
      "Being the first accessory of Hatha Yoga, āsana is described first.",
      "Just as sparing food is among Yamas, and Ahimsâ among the Niyamas, so is Siddhâsana called by adepts the chief of all the âsanas.",
      "There is no âsana like the Siddhâsana and no Kumbhaka like the Kevala.",
    ],
  },
  {
    pattern: /[sś]iva.?sa[mṃ]hit[aā]|shiva.?samhita/i,
    quotes: [
      "In this body is the sacred Ganges, here the sun and moon, here the holy places — why go elsewhere?",
      "When the sleeping kuṇḍalinī is awakened, the way to liberation opens.",
      "The mind is the cause of bondage and the mind is the cause of liberation.",
      "He who knows the self as the witness of all, remaining unattached, is free.",
      "The lotus of the heart is the dwelling of the Self; there the yogi should rest.",
      "The jnana Gnosis alone is eternal; it is without beginning or end; there exists no other real substance.",
      "That Intelligence, which incites the functions into the paths of virtue or vice, am I.",
      "As, when the knowledge of the rope is obtained, the erroneous notion of its being a snake does not remain; so, by the arising of the knowledge of self.",
      "From Devas down to this material universe all are pervaded by one Spirit.",
      "Since by Gnosis is destroyed the Ignorance, which is the cause of the universe; therefore, the Spirit is Gnosis; and this Gnosis is consequently eternal.",
    ],
  },
  {
    pattern: /vijnana.?bhairava|vij[nñ][aā]na.?bhairava/i,
    quotes: [
      "Bhairava is not found in ritual, nor in pilgrimage, nor in the recitation of mantras.",
      "When the breath is held at the end of inhalation or exhalation, the terrific one is revealed.",
      "If one contemplates the universe as a painting, the supreme awakening dawns.",
      "The bliss that arises when two gazes meet — that too is the meditation.",
      "Wherever the mind finds satisfaction, there, just there, contemplate the Self.",
      "By blocking perception with the hand-weapon kara-ruddha-dṛg-astra, piercing the eyebrow-center bhrū-bheda and sealing the doors dvāra-rodhana, when the.",
      "With the sense-faculties dissolved in the space of the heart hṛdyākāśe nilīnākṣaḥ, stationed in the middle of the lotus-whorl padmasampuṭamadhyagaḥ, with.",
      "Meditating on the principles of reality tattvāni—those progressively more subtle sūkṣmasūkṣmatarāṇi—as they dissolve into their resting place nilayaṃ within.",
      "The pleasure that arises from the union of energies śakti-saṃgama, which agitates and culminates in the immersion into Energy śaktyāveśa, is the very bliss.",
      "On a soft seat mṛdvāsane, placing the hands and feet without support nirāśrayam, with only the buttocks sphij- as contact, through abiding in that state.",
    ],
  },
  {
    pattern: /siva.?s[uū]tra|[sś]iva.?s[uū]tra|shiva.?sutra/i,
    quotes: [
      "Caitanyam ātmā — consciousness itself is the Self.",
      "Knowledge is bondage.",
      "The unfolding of the center is the way.",
      "By union with the power of the will, the world appears.",
      "The waking world is a play of awareness; dream is its inner theatre.",
      "Consciousness is the Self.",
      "The bliss of the world is the joy of samādhi.",
      "The union of elements, the separation of elements, and the collisions of the universe.",
      "The surge of awareness is Bhairava.",
      "When knowledge withdraws, dreamlike perception arises from it.",
    ],
  },
  {
    pattern: /spanda/i,
    quotes: [
      "The spanda is the slight movement of the unmoving.",
      "That in which the universe shines, and which shines in the universe — that is the throb.",
      "When the yogi finds the spanda, he stands as the enjoyer of the arising and dissolving of all.",
      "Even in anger, even in joy, even in a sudden fright — there the spanda can be seized.",
      "Established in the throb, one is never a victim of the next thought.",
      "Even within the differentiation of waking and other states jāgradādi vibheda, it flows undivided tadabhinne prasarpati.",
      "Verse 6: Because this aggregate of faculties, though confused, acts by itself like one who is unconfused, along with the inner wheel of prāṇa, there is.",
      "Then his innate, unconditioned nature—characterized by knowing-subjectivity and agency jñātṛ-kartṛtva—becomes manifest.",
      "Here the pair of states is called 'effect-hood and agent-hood' kāryakartṛtva.",
      "United with the supreme power śakti whose nature is knowledge and the knowable jñānajñeya, the all-pervading one vibhu shines in the pair of states.",
    ],
  },
  {
    pattern: /pratyabhij/i,
    quotes: [
      "Consciousness, of its own free will, unfolds the universe upon its own screen.",
      "The Self is already accomplished; recognition is not a becoming.",
      "When one knows 'I am Śiva,' the world is no longer a cage.",
      "Independence is the very nature of awareness.",
      "When the Lord is recognized as one's own Self, the universe becomes a play.",
      "Consciousness, being autonomous, is the cause of the perfection of the universe.",
      "The individual experient, in whom Consciousness has contracted, also contains the universe — but in a contracted form.",
      "Consciousness itself, having descended from the state of pure sentience, becomes the individual mind contracted by objects of cognition.",
      "And though He — the Supreme Self — is One, He becomes double, triple, fourfold, and of the nature of seven groups of five.",
      "That — the Self full of Consciousness — becomes the transmigratory soul, covered by Mala, through contraction of its Śakti.",
    ],
  },
  {
    pattern: /tantras[aā]ra|abhinavagupta/i,
    quotes: [
      "The heart is the resting place of all, and from the heart all this shines forth.",
      "Recognition is not gained; it is uncovered.",
      "The universe is the overflowing of one's own consciousness.",
      "He who tastes the aesthetic flash (camatkāra) tastes the Self.",
      "Nothing exists that is not Śiva; to know this is to be free.",
      "May there shine forth the Heart consisting of the emission of being, flashing as the inseparable divine Pair: the Mother, the great begetter of ever-new.",
      "But when one who has been pierced by the descent of intense Śakti discerns in this manner by himself, having comprehended the guru's teaching just once.",
      "“Thus, just as this thing appears as a reflection, so too does the universe appear in the light prakāśa of the Supreme Lord Parameśvara.”.",
      "For without self-apprehension of its own nature, there would in truth be mere insentience.",
      "For the attainment of the firmly established contemplative awareness that 'all entities are constituted of the radiance of the Supreme Lord,' homa is the.",
    ],
  },
  {
    pattern: /yogin[iī]h[rṛ]daya|yogini.?hrdaya|heart of the yogini/i,
    quotes: [
      "The heart of the yoginī is the triangle of desire, knowledge, and action.",
      "She who is the pulse of the three cities dwells as one's own awareness.",
      "The śrīcakra is not drawn on the ground; it is the body of consciousness.",
      "When the mantra is known as one's own throb, the goddess is no other.",
      "The bindu is the secret of the three; in it the goddess rests.",
      "God of gods, Great God, you whose very being is total fullness unfolding — in this Vāmakeśvara teaching many meanings remain unknown ajñātārtha.",
      "Listen, Goddess, to the great secret — the supreme Heart of the Yoginī.",
      "Supreme Sovereign — the saṃketa of the goddess Tripurā is threefold: the co-presence within the cakra, and likewise those within the mantra and within the.",
      "So long as one does not know this supreme triad of co-presences, just so long one does not become a bearer of the highest authority paramājñā within.",
      "Its five energies tend toward emission sṛṣṭi; its four fires, toward resorption laya.",
    ],
  },
  {
    pattern: /vajracchedik|diamond.?s[uū]tra/i,
    quotes: [
      "A bodhisattva should produce a mind that does not dwell anywhere.",
      "This is how to contemplate this fleeting world: a star at dawn, a bubble in a stream.",
      "Those who see me by form, who seek me by sound — they walk a false path.",
      "The Tathāgata cannot be seen by means of the possession of attributes.",
      "All composed things are like a dream, a phantom, a drop of dew, a flash of lightning.",
      "Then, in the early part of the day, the Blessed One dressed, took up his bowl and robe, and entered the great city of Śrāvastī to seek alms.",
      "If the notion of a being were to operate in a bodhisattva, Subhūti, that person could not be called a bodhisattva.",
      "“What do you think, Subhūti: is the Tathāgata to be seen through the perfection of his marks?” Subhūti said, “No indeed, Blessed One.",
      "Then again the Blessed One said to the venerable Subhūti: “What do you think, Subhūti?",
      "The Blessed One said: “What do you think, Subhūti?",
    ],
  },
  {
    pattern: /heart.?s[uū]tra/i,
    quotes: [
      "Form is emptiness; emptiness is form.",
      "Gone, gone, gone beyond, gone completely beyond — awakening, svāhā.",
      "No old age and death, and also no end of old age and death.",
      "All dharmas are marked by emptiness — not born, not destroyed, not stained, not pure.",
      "There is no suffering, no origination, no stopping, no path.",
      "There is no knowing, no attaining, and no failing-to-attain.",
      "This is the mantra it speaks: gate gate pāragate pārasaṃgate bodhi svāhā—gone, gone, gone over, gone entirely over to the far shore; awakening; so be it.",
    ],
  },
  {
    pattern: /dhammapada/i,
    quotes: [
      "Mind precedes all things; mind is their chief; they are mind-made.",
      "Better than a thousand hollow words is one word that brings peace.",
      "Hatred is never appeased by hatred; by non-hatred alone is it appeased.",
      "You yourself must strive. The Buddhas only point the way.",
      "Drop by drop is the water pot filled; likewise the sage fills himself with good.",
      "116 If a man would hasten towards the good, he should keep his thought away from evil; if a man does what is good slothfully, his mind delights in evil.",
      "197 Let us live happily then, not hating those who hate us!",
      "The Pair Chapter is complete.",
      "For the way that leads to gain is one thing, and the way that leads toward nibbāna is another.",
      "145 Irrigators guide water; arrow-makers bend the shaft; carpenters shape wood.",
    ],
  },
  {
    pattern: /nagarjuna|n[aā]g[aā]rjuna|madhyamaka|mulamadhyamaka/i,
    quotes: [
      "Whatever is dependently arisen, that is explained to be emptiness.",
      "There is not the slightest difference between saṃsāra and nirvāṇa.",
      "I prostrate to the Perfect Buddha, the best of teachers, who taught that whatever is dependently arisen is unceasing, unborn.",
      "If nirvāṇa were something, it would be conditioned. If it were nothing, how could it be nirvāṇa?",
      "Emptiness wrongly grasped is like picking up a poisonous snake.",
      "Now if that effect, though nonexistent, proceeds from those conditions, why does the result not likewise proceed from nonconditions?",
      "Just as the arising of a son is spoken of in dependence upon mother and father, so the arising of consciousness is spoken of in dependence upon eye and.",
      "When an existent is not present, whose nonexistent will there be?",
      "If the distinct separateness of passion and the passionate person were already established, why would you then conceive their being together?",
      "What has gone gata is not traversed; what has not gone agata is likewise not traversed.",
    ],
  },
  {
    pattern: /shantideva|[sś][aā]ntideva|bodhicary/i,
    quotes: [
      "All the suffering in the world comes from seeking pleasure for oneself. All the happiness comes from seeking pleasure for others.",
      "Where would I find enough leather to cover the earth? But leather on the soles of my shoes is enough.",
      "If the problem can be solved, why worry? If it cannot be solved, worrying will do no good.",
      "As long as space remains, as long as sentient beings remain, may I too remain to dispel the miseries of the world.",
      "May I be a guard for those who are protectorless, a guide for those who journey on the road.",
      "Having reverently bowed to the Sugatas Well-Gone Ones, together with their sons and their Dharma-bodies, and to all who are worthy of veneration, I shall.",
      "To obtain that jewel of mind cittaratna, I here make proper worship pūjā of the Tathāgatas, of the stainless jewel of the true Dharma saddharma, and of the.",
      "Having thus done all this, whatever goodness śubha I have attained, may I thereby become one who brings the complete calming praśānti of every suffering to.",
      "One who wishes to guard the training śikṣā should diligently guard the mind citta.",
      "All this good conduct—giving dāna and worship of the Sugatas—performed through thousands of eons: anger pratigha destroys it.",
    ],
  },
  {
    pattern: /d[oō]gen|shobogenzo|sh[oō]b[oō]genz[oō]/i,
    quotes: [
      "To study the Buddha Way is to study the self. To study the self is to forget the self.",
      "Time is not a line. The time of a pine is a pine; the time of a bamboo is a bamboo.",
      "If you cannot find the truth right where you are, where else do you expect to find it?",
      "A fish swims in the ocean, and no matter how far it swims, there is no end to the water.",
      "Enlightenment is like the moon reflected in water. The moon does not get wet, nor is the water broken.",
      "When all dharmas are the Buddha-dharma, then there is delusion and realization, practice, birth and death, buddhas and sentient beings.",
      "To carry the self forward and practice-realize the myriad dharmas is delusion.",
      "When a person first seeks the dharma, they are far removed from the dharma's borders.",
      "It does not become firewood again.",
      "Realization is like the moon reflected in water.",
    ],
  },
  {
    pattern: /milarepa/i,
    quotes: [
      "The more I meditate, the more unmistakable the nature of mind becomes.",
      "In the gap between two thoughts, the innate face of mind is seen.",
      "When I look, I find nothing. When I rest, it is vividly present.",
      "Do not seek the Buddha elsewhere; he is the one who is looking.",
      "My religion is to live and die without regret.",
      "I sing this song of liberation from the eight worldly dharmas.",
      "The cave feeds me with emptiness; the rocks are my companions.",
      "Hunter, listen well: this deer, driven by terror, has come to this yogin seeking refuge.",
      "Enable me to give up worldly aims.",
      "In the sacred guru's grace and the zealous disciple's active meditation lies opportunity to uphold the Truth; of this, the essence is purity of faith.",
    ],
  },
  {
    pattern: /tilopa|maha.?mudra/i,
    quotes: [
      "Do not imagine, do not think, do not analyze, do not meditate, do not reflect — rest naturally.",
      "Like a river flowing into the ocean, let the mind rest in its own place.",
      "Mahāmudrā is not a thing to be attained; it is the nature of what is already looking.",
      "Cut the root of a tree and the branches wither. Cut the root of mind and all appearance is freed.",
      "Look at the mind; there is nothing to see. Seeing nothing, see its nature.",
      "Mahāmudrā cannot be pointed to by any symbol, and the ordinary mind cannot grasp it as an object of thought.",
      "Just as space cannot be indicated with a finger or fenced in by a border, the nature of mind sems nyid has no center and no circumference.",
      "Whoever spends their effort completely and then rests in devotion to the guru bla ma will see the innate sahaja.",
      "Mantra recitation, the perfections pāramitā, Vinaya, sūtras, the collections of teachings, and the rest.",
      "Beyond the field of apprehended objects, mind’s own nature is lucid rang bzhin.",
    ],
  },
  {
    pattern: /tao.?te.?ching|dao.?de.?jing|lao.?tzu/i,
    quotes: [
      "The way that can be spoken is not the constant Way.",
      "The sage does nothing, yet nothing is left undone.",
      "Know the white, keep the black; be a pattern to the world.",
      "Heaven and earth are not kind; they treat the ten thousand things as straw dogs.",
      "Returning is the movement of the Way; yielding is its function.",
      "The dào is constant cháng 常: wúwéi — and yet nothing is left undone wú bù wéi 無不為.",
      "In pursuing the dào, daily diminish rì sǔn 日損.",
      "The Dao is empty, yet in using it, it is never exhausted.",
      "When the Great Way dàdào 大道 Way or Method ceased to be observed, benevolence and righteousness came into vogue.",
      "When one wishes to take the world and act upon it, I see that this cannot succeed.",
    ],
  },
  {
    pattern: /chuang|zhuang/i,
    quotes: [
      "Once I, Zhuang Zhou, dreamed I was a butterfly. Or was I a butterfly dreaming I was Zhuang Zhou?",
      "The perfect man uses his mind like a mirror — it grasps nothing, it refuses nothing.",
      "You cannot speak of ocean to a well-frog.",
      "Forget the years, forget distinctions. Leap into the boundless and make it your home.",
      "The torch of chaos and doubt — this is what the sage steers by.",
      "Zhuangzi and Huizi were strolling on the bridge over the Hao River.",
      "T'ien Zi Fang was in attendance upon Prince Wên of Wei.",
      "He ravaged the whole empire, plundering the various nobles and breaking into people's houses.",
      "Once, Zhuang Zhou dreamt he was a butterfly - vividly, joyfully butterfly, moving exactly as butterfly-nature moves.",
      "Those who dream of feasting wake grieving; those who dream of grief wake into pursuit and excitement.",
    ],
  },
  {
    pattern: /confucius|analect/i,
    quotes: [
      "The Master said: To learn and at due times to repeat what one has learnt, is that not after all a pleasure?",
      "Do not impose on others what you yourself do not desire.",
      "The junzi is not a utensil.",
      "When I walk along with two others, they may serve me as my teachers.",
      "Is it not a joy to have friends come from afar?",
      "The Master said: “The junzi completes what is beautiful in others; he does not complete what is bad in others.",
      "The philosopher Zeng said, 'I daily examine myself on three points:—whether, in transacting business for others, I may have been not faithful;—whether, in.",
      "The Master said, 'If the scholar be not grave, he will not call forth any veneration, and his learning will not be solid.",
      "The Master said, 'Shen, my doctrine is that of an all-pervading unity.' The disciple Zeng replied, 'Yes.' The Master went out, and the other disciples.",
      "When the accomplishments and solid qualities are equally blended, we then have the man of virtue.'.",
    ],
  },
  {
    pattern: /zhongyong|doctrine of the mean/i,
    quotes: [
      "What Heaven confers is called the nature; accordance with this nature is called the Way.",
      "Equilibrium is the great root of the world; harmony is the universal path.",
      "Sincerity is the Way of Heaven; to become sincere is the Way of the human.",
      "The Way is not far from the human. If a person takes a way far from the human, it cannot be the Way.",
      "The junzi is watchful over himself when he is alone.",
      "Sincerity cheng is the Way of Heaven; to become sincere is the Way of the human being.",
      "The Way of Heaven and Earth can be summed up in a single phrase: their operation is without duality bù èr, therefore their generation of things is unfathomable.",
      "The path may not be left for an instant.",
      "The Master said, 'I know how it is that the path of the Mean is not walked in:—The knowing go beyond it, and the stupid do not come up to it.",
      "The Master said, 'The Way is not far from people.",
    ],
  },
  {
    pattern: /heraclitus/i,
    quotes: [
      "You cannot step twice into the same river.",
      "The unseen harmony is stronger than the seen.",
      "Nature loves to hide.",
      "The way up and the way down are one and the same.",
      "Listening not to me but to the Logos, it is wise to agree that all things are one.",
      "Polybius iv. 40. Especially at the present time, when all places are accessible either by land or by water, we should not accept poets and mythologists as.",
      "The cosmos, shared by all, has not been created by any god or human; instead, it has always existed, exists now, and will continue to exist as an.",
      "Heraclitus and Democritus also bear witness to him.",
      "Both good and evil are one. For physicians, says Heraclitus, cutting and burning and torturing the sick badly in every way, complain that they receive no.",
      "One must understand that war is common to all, and that justice is strife, and that all things come to be in accordance with strife and necessity.",
    ],
  },
  {
    pattern: /parmenides/i,
    quotes: [
      "What is, is; what is not, is not.",
      "It is the same thing to think and to be.",
      "Being is ungenerated and imperishable, whole, unique, unmoved, and complete.",
      "Never shall this prevail: that things that are not, are.",
      "Look upon what is absent as if it were steadfastly present to the mind.",
      "You shall know the ether’s nature, and every sign within the ether; the unseen works of the pure, blazing torch of the sun, and whence they came to be.",
      "For the narrower ones were filled with unmixed fire; those next to them, with night; and amid them a portion of flame courses.",
      "Ever gazing toward the beams of the sun.",
      "For what is in greater measure is thought.",
      "See, with the mind, absent things nonetheless steadily present; for you will not cut off what-is from clinging to what-is—neither as scattered everywhere.",
    ],
  },
  {
    pattern: /epictetus/i,
    quotes: [
      "Some things are up to us, and some things are not up to us.",
      "It is not things that disturb us, but our judgments about things.",
      "Do not seek to have events happen as you wish, but wish them to happen as they do.",
      "If you want to improve, be content to be thought foolish and stupid.",
      "Make the best use of what is in your power, and take the rest as it happens.",
      "Sickness is a hindrance to the body, but not to your ability to choose, unless that is your choice.",
      "Remember, that not he who gives ill language or a blow insults, but the principle which represents these things as insulting.",
      "Of existing things, some are up to us, others are not up to us.",
      "With every event that comes upon you, remember to turn back to yourself and ask what power you possess for using it well.",
      "Whenever you find yourself turning outward because you want to please someone, know that you have lost your footing.",
    ],
  },
  {
    pattern: /marcus|meditations/i,
    quotes: [
      "The universe is transformation; life is opinion.",
      "Waste no more time arguing what a good man should be. Be one.",
      "You have power over your mind — not outside events. Realize this, and you will find strength.",
      "What is not good for the hive is not good for the bee.",
      "Soon you will have forgotten all; soon all will have forgotten you.",
      "At every hour, take care to do what lies in your hands firmly—as a Roman and a man—with exact and unfeigned dignity, affection, freedom, and justice; and.",
      "Revere the faculty by which you form judgments.",
      "Remove the judgment, and “I have been harmed” is removed.",
      "Do not live as though you were about to live ten thousand years.",
      "Either the universe is an ordered arrangement, or a muddled mixture.",
    ],
  },
  {
    pattern: /phaedo|plato/i,
    quotes: [
      "The one aim of those who practice philosophy in the proper manner is to practice for dying and death.",
      "Cebes, I believe that the soul is immortal and imperishable.",
      "We shall part from here as from a prison.",
      "If the soul is immortal, it requires our care not only for this time, but for all time.",
      "Crito, we owe a cock to Asclepius. Pay it and do not neglect it.",
      "The philosopher does not practice death as mere cessation but engages in the very act of dying.",
      "Learning is presented as recollection: the mind does not manufacture first principles from scratch but re-recognizes standards it already measures by.",
      "Socrates argues by affinity: what is composite and visible tends toward dissolution; what is simple and intelligible tends toward endurance.",
      "Simmias proposes that the soul is like harmony: subtle, invisible, but dependent on bodily structure as harmony depends on strings.",
      "After disappointment with physical speculation, Socrates undertakes a \"second sailing\": from sensory causes to intelligible explanation.",
    ],
  },
  {
    pattern: /plotinus|ennead/i,
    quotes: [
      "Never did the eye see the sun unless it had first become sunlike.",
      "Withdraw into yourself and look. If you do not find yourself beautiful yet, act as the creator of a statue.",
      "The One is all things and no one of them.",
      "We are always around it, but we do not always look.",
      "Cut away everything.",
      "Beauty is found most of all in what is seen, but it is also in what is heard, in the composition of words, and also in music of every kind; for melodies and.",
      "The soul possesses an intrinsic faculty for discerning beauty, one that is unwavering and unshakeable, never doubting its own judgement when confronted with.",
      "When perceiving beautiful forms in the physical world, do not pursue them, for they are mere eidolon εἴδωλον - copies, remnants, and shadows of the true Beauty.",
      "As the soul permeates all of existence, it brings light and immortality to the material world, transforming it into a living, blessed, and harmonious system.",
      "The Intellectual-Principle perceives and thinks, but how does it come to be from the One, which then becomes its object of thought?",
    ],
  },
  {
    pattern: /eckhart/i,
    quotes: [
      "The eye with which I see God is the same eye with which God sees me.",
      "Detachment is the best of all, for it makes us one with God.",
      "God is a word, an unspoken word.",
      "The just man serves neither God nor creatures, for he is free.",
      "The shell must be cracked apart if what is in it is to come out.",
      "And as far as reason can search and know, I find nothing other than this: pure detachment lûteriu abegescheidenheit stands above all things.",
      "I praise detachment Abgeschiedenheit above every virtue.",
      "The masters also praise humility above many other virtues.",
      "So long as you hold yourself back—so long as you cling to your own will, your own understanding, your own desire—God cannot work purely in you.",
      "There is a power in the soul so noble and so pure that it remains wholly untouched by time and flesh.",
    ],
  },
  {
    pattern: /dionysius|areopagite|mystical.?theology|divine.?names/i,
    quotes: [
      "Leave behind the senses and the operations of the intellect; leave behind all things, and stretch toward union with the unknown.",
      "The cause of all is itself no one of all.",
      "Into the dark beyond all light, we pass, unseeing and unknowing.",
      "It is not soul or mind, nor number or order, nor greatness or smallness.",
      "The higher we soar, the more our words are confined to the ideas we are contemplating.",
      "Concerning this superessential and hidden Godhead, then, as has been said, we must not dare either to speak or even to conceive anything beyond what has.",
      "Distinct, however, are the supra-essential name and reality of Father, Son, and Spirit, with no interchange or any commonality at all introduced among these.",
      "Yet the most manifest reality of all theology—the God-fashioning of Jesus in our midst—is beyond utterance for every word and unknown to every mind, even to.",
      "But if, as indeed it is, the Good is beyond all beings, then it also gives form to what is without form.",
      "The divine minds, then, are said to be moved: in a circle, as they are unified with the beginningless and endless illuminations of the Beautiful and the.",
    ],
  },
  {
    pattern: /cloud.?of.?unknowing/i,
    quotes: [
      "Beat upon that thick cloud of unknowing with a sharp dart of longing love.",
      "By love He may be gotten and holden; but by thought never.",
      "Look that nothing live in thy working mind but a naked intent stretching unto God.",
      "Humble prayer continues to pierce the cloud; thought cannot.",
      "God may well be loved, but not thought.",
      "And therefore I would leave all that I can think, and choose for my love that which I cannot think.",
      "But now you ask me and say, 'How shall I think on him, and what is he?' And to this I can only answer thus: 'I do not know.' For you have brought me with.",
      "And therefore travail hard against all sudden thoughts that come from these, and put them down as often as you may.",
      "Ou, how clearly doth our author here deliver the true doctrine about the use of extra- ordinary favours!",
      "HERE he speaketh still of the efficacy of those aspirations with God.",
    ],
  },
  {
    pattern: /gospel.?of.?thomas/i,
    quotes: [
      "The kingdom is inside you, and it is outside you.",
      "Split a piece of wood; I am there. Lift the stone, and you will find me there.",
      "If you bring forth what is within you, what you bring forth will save you.",
      "The one who seeks should not stop until they find. When they find, they will be disturbed.",
      "Jesus said: Become passers-by.",
      "And he said: “A person is like a wise fisherman who cast his net into the sea.",
      "For there will be five in a house: three will be against two, and two against three; father against son, and son against father.",
      "The disciples said to Jesus, “Tell us: to whom is the kingdom of heaven comparable?” He said to them, “It is like a mustard seed, smaller than all seeds.",
      "There is light within a person of light, and he illuminates the entire world.",
      "Jesus said, “What you hear in one ear, proclaim from the other upon your rooftops.",
    ],
  },
  {
    pattern: /course in miracles|acim/i,
    quotes: [
      "Nothing real can be threatened. Nothing unreal exists. Herein lies the peace of God.",
      "I am not a body. I am free. For I am still as God created me.",
      "Forgiveness is the key to happiness.",
      "Teach only love, for that is what you are.",
      "You who want peace can find it only by complete forgiveness.",
    ],
  },
  {
    pattern: /ecclesiastes|qoheleth/i,
    quotes: [
      "Vanity of vanities, says Qoheleth; vanity of vanities, all is vanity.",
      "To every thing there is a season, and a time to every purpose under heaven.",
      "The race is not to the swift, nor the battle to the strong.",
      "Fear God, and keep his commandments: for this is the whole of the human.",
      "The dust returns to the earth as it was, and the spirit returns to God who gave it.",
      "I came to know that this too is a pursuit of wind.",
      "This also is vapor and a chasing of wind.",
      "Who knows whether the breath of humankind rises upward, while the breath of the beast goes down into the earth?",
      "There is no end to all the people—to all who were before them; yet those who come later will not rejoice in him.",
      "Even if one lived a thousand years twice over, yet saw no good, do not all go to one and the same place?",
    ],
  },
  {
    pattern: /ibn|arabi|balyani|know yourself/i,
    quotes: [
      "He who knows himself knows his Lord.",
      "There is nothing in existence but God.",
      "You are not you; you are He, without you.",
      "The world is imagination within imagination — and the Real is the one who imagines.",
      "The Real is the mirror; you are the form that appears in it.",
      "Surely We created the human being, and We know what his self whispers within him; and We are nearer to him than the jugular vein.",
      "The before and the after are His; and He is now as He was.",
      "No one sees Him except Himself, no one reaches Him except Himself and no one knows Him except Himself.",
      "His being is concealed by His oneness without any condition.",
      "He sent Himself from Himself, through Himself to Himself.",
    ],
  },
  {
    pattern: /rumi|r[uū]m[iī]|mathnawi|mathnaw[iī]/i,
    quotes: [
      "The wound is the place where the Light enters you.",
      "You were born with wings. Why prefer to crawl through life?",
      "Silence is the language of God; all else is poor translation.",
      "Don't get lost in your pain; know that one day your pain will become your cure.",
      "Try to appear as you are, or be as you appear.",
      "Listen to this reed, how it complains, how it tells the story of separations: 'Ever since I was cut from the reed-bed, men and women have lamented in my cry.'.",
      "An elephant was in a dark house; the Indians had brought it for exhibition.",
      "A drop had separated from the Ocean, ashamed of its smallness.",
      "That Sun of Tabriz whose radiance illumined all the world—He is the Light of Light, and we are moths before His fire.",
      "I have already died a thousand times in longing for you.",
    ],
  },
  {
    pattern: /eastman|soul of the indian|ohiyesa/i,
    quotes: [
      "The native soul was not a wanderer; it was at home in the Great Mystery.",
      "Silence is the cornerstone of character.",
      "In the life of the Indian there was only one inevitable duty — the duty of prayer.",
      "The first American mingled with his pride a singular humility.",
      "It was not a religion of one day, but of every day, of every act.",
    ],
  },
  {
    pattern: /zitkala|old indian legends/i,
    quotes: [
      "Iktomi, the avaricious, is a spider still.",
      "The old legends were not told to fill an hour, but to shape a people.",
      "Under the listening stars the stories walked again.",
      "What the firelight knows, the page can only borrow.",
      "Iktomi is always hungry, always clever, and always caught in his own web.",
    ],
  },
  {
    pattern: /johnson|yoruba.?faith|yoruba.?religion/i,
    quotes: [
      "Olódùmarè is the origin of all that is, and of all that will be.",
      "The òrìṣà are not rivals of the One; they are faces of the One in the world.",
      "Character is the shining of a person; without it, ritual is empty.",
      "Ifá does not speak to flatter; Ifá speaks so that the path may be walked.",
      "The Yoruba say that character is the finest beauty of a person.",
      "Orisarowu at Owu Orisajaye at Ijaye.",
      "Mohammedanism which many now profess was introduced only since the close of the eighteenth century.",
      "Thus the httle children perpetuate the memory and worship of this deity, hence the ditty .",
      "It is from this notion that some children are named \" Babatunde,\" i.e., father comes again.",
      "The representing image is the silk cotton tree specially planted.",
    ],
  },
  {
    pattern: /yoruba|[oò]we/i,
    quotes: [
      "The world is a marketplace; heaven is home.",
      "Slowly, slowly the pepper becomes ripe.",
      "The river that forgets its source will dry up.",
      "What an elder sees while seated, a child cannot see even from the top of a tree.",
      "When the drumbeat changes, the dance must change also.",
      "He who has done something in secret, and sees people talking together, thinks they are talking of his action.",
      "A eliarp word is as tough aa a bow-string.",
      "A man of the town knows nothing about farm- ing, or the seasons for planting, yet the yam he buys must always be large.",
      "To be trodden upon here, to be trodden upon there, is the fate of the palra-kemel lying in the road.",
      "A gift is a gift, and a purchase is a purchase ; so no one will thank you for saying \" I sold it you very cheap.\".",
    ],
  },
  {
    pattern: /kabbalah|zohar|yetzirah|sephiroth|sefirot/i,
    quotes: [
      "Ten sefirot of nothingness, twenty-two foundation letters.",
      "The Infinite is not a thing among things; it is that from which things arise.",
      "As above, so below — the tree is one.",
      "He engraved and carved and created His world in thirty-two mysterious paths of wisdom.",
      "Before the emanations were emanated, there was only the Infinite.",
      "In two and thirty most occult and wonderful paths of wisdom did JAH the Lord of Hosts engrave his name: God of the armies of Israel, ever-living God.",
      "The ten numbers formed from nothing are the Decad: these are seen in the fingers of the hands, five on one, five on the other, and over them is the Covenant.",
      "These Ten Numbers, beyond the Infinite one, have the boundless realms, boundless origin and end, an abyss of good and one of evil, boundless height and.",
      "And as to this Decad of the Sephiroth, restrain thy lips from comment, and thy mind from thought of them, and if thy heart fail thee return to thy place.",
      "Second, from the Spirit he made Air and formed for speech twenty-two letters, three of which are mothers, A, M, SH, seven are double, B, G, D, K, P, R, T.",
    ],
  },
];

export const HERO_QUOTE_DWELL_MS = 18_000;

function uniqueLines(lines: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of lines) {
    const line = raw.replace(/\s+/g, " ").trim();
    if (line.length < 24 || line.length > 160) continue;
    const key = line.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(line);
  }
  return out;
}

/** Curated lines for a collection, else a short fallback list from the catalog. */
export function heroQuotesFor(collection: string, fallback: string[] = []): string[] {
  const raw = (collection || "").trim();
  if (!raw || raw.toLowerCase() === "all") return [];
  for (const row of HERO_QUOTES) {
    if (row.pattern.test(raw)) return row.quotes;
  }
  return uniqueLines(fallback).slice(0, 10);
}

/** First sentences from catalog translations, filtered to mandala length. */
export function catalogQuoteCandidates(lines: string[]): string[] {
  return uniqueLines(lines).slice(0, 10);
}

/** Next index in a random walk — never the line already showing. */
export function nextHeroQuoteIndex(current: number, length: number): number {
  if (length < 2) return 0;
  const step = Math.floor(Math.random() * (length - 1));
  return step >= current ? step + 1 : step;
}
