name: Pratibha
options:
  bundleIdPrefix: com.semantikmatch
  deploymentTarget:
    iOS: "26.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "2"
    GENERATE_INFOPLIST_FILE: YES
    DEVELOPMENT_TEAM: "HKXSRXV4K5"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    SWIFT_EMIT_LOC_STRINGS: YES

targets:
  Pratibha:
    type: application
    platform: iOS
    sources:
      - path: Pratibha
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.apekode.pratibha
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_KEY_CFBundleDisplayName: "Pratibhā"
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
